"""crfix table

Revision ID: d22f610dee1b
Revises: 369ac1ae08b7
Create Date: 2020-12-26 23:03:41.619732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22f610dee1b'
down_revision = '369ac1ae08b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albumPhotos', sa.Column('album_id', sa.Integer(), nullable=True))
    op.add_column('albumPhotos', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.drop_constraint('albumPhotos_id_fkey', 'albumPhotos', type_='foreignkey')
    op.create_foreign_key(None, 'albumPhotos', 'albums', ['album_id'], ['id'])
    op.create_foreign_key(None, 'albumPhotos', 'photos', ['photo_id'], ['id'])
    op.drop_column('albumPhotos', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albumPhotos', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'albumPhotos', type_='foreignkey')
    op.drop_constraint(None, 'albumPhotos', type_='foreignkey')
    op.create_foreign_key('albumPhotos_id_fkey', 'albumPhotos', 'albums', ['id'], ['id'])
    op.drop_column('albumPhotos', 'photo_id')
    op.drop_column('albumPhotos', 'album_id')
    # ### end Alembic commands ###
